joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

base_controller:
  type             : "diff_drive_controller/DiffDriveController"
  left_wheel       : ['rear_left_wheel_joint', 'front_left_wheel_joint']
  right_wheel      : ['rear_right_wheel_joint', 'front_right_wheel_joint']
  publish_rate     : 50.0
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  enable_odom_tf: true

  cmd_vel_timeout: 0.5

  base_frame_id: base_footprint #default: base_link
  odom_frame_id: odom

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.2 # m/s
      # min_velocity           : -0.15 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.8  # m/s^2
      # min_acceleration       : -1.6 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0  # rad/s^2